module.exports = {
    _DEFAULT_SORT_COLUMNS: ["sortOrder"],
    _COUNTRY_COLUMNS: ["iso2code", "displayName"],
    _SUBDIVISION_COLUMNS: ["code", "name", "abbreviation"],
    _CATEGORY_COLS: ["id", "name", "sortOrder", "parentId"],
    _PRODUCT_IMAGE_COLS: ["id", "productId", "image", "sortOrder"],
    _PRODUCT_COLS: ["id", "name", "sku", "description", "status", "unitsId", "unitPrice", "delivery", 
    "supplierId", "priceExpirationDate", "minimumPurchaseAmount", "isTaxable", "inventoryAvailable",
    "newPrice", "newPriceStartDate", "newPriceExpirationDate"],
    _DRIVE_COLS: ["id", "userId", "groupId", "name", "desc", "closeDate", "status", "canDonateThroughRoonga", 
    "canDonateOffline", "template", "taxRate", "editDate", "launchDate", "friendlyUrl", "enableDonorReport", 
    "buyGiveDrive", "thankYouEmailTemplate", "currencyId", "driveType", "adoptionEndDate", "amazonUrl"],
    _DRIVE_PRODUCT_COLS: ["id", "driveId", "driveCategoryId", "productId", "name", "description", 
    "unitPrice", "quantity", "quantityRemaining","minimumPurchaseAmount", "sortOrder"],
    _DRIVE_CATEGORY_COLS: ["id", "driveId", "name", "sortOrder"],
    _DRIVE_MEDIA_COLS: ["id", "driveId", "url", "isImage"],
    _DRIVE_DELIVERY_INFO_COLS: ["id", "driveId", "contactName", "contactNumber", "deliveryDate", "streetAddress", 
    "city", "state", "zip", "mapAddress", "mapPinLabel", "lat", "lng"],
    _ADOPTION_DRIVE_CONFIG_COLS: ["id", "driveId", "giftRequestsByAdminOnly", "instructions", "maxGiftPrice", 
    "notAllowedItems", "wrapRequirements", "labellingRequirements", "dropoffAddress", "dropoffDateFrom", 
    "dropoffDateTo", "dropoffHoursFrom", "dropoffHoursTo", "dropoffByAppointmentOnly", 
    "alternativeDropoffContact", "alternativeDropoffContactPhone", "alternativeDropoffContactEmail", 
    "additionalInfo", "adoptionDriveType", "isFamily", "isIndividual", "autogenProfileIdType"],
    _ADOPTION_DRIVE_PROFILE_COLS: ["id", "driveId", "autogenProfileId", "contactFirstName", "contactLastName", 
    "profileDescription", "profileStatus", "profileImageId", "profileTypeId"],
    _ADOPTION_DRIVE_PROFILE_MEMBER_COLS: ["id", "driveId", "adoptionDriveProfileId", "memberName", 
    "genderId", "roleId", "age", "ageCategory", "additionalInfo"],
    _ADOPTION_DRIVE_PROFILE_MEMBER_ITEM_COLS: ["id", "driveId", "adoptionDriveProfileMemberId", 
    "itemTypeId", "itemDesc", "itemSize", "itemStyle", "itemColor"],
    _ADOPTION_DRIVE_PROFILE_SETUP_USER_COLS: ["id", "driveId", "userId", "groupId", "statusId"],
    _USER_RESPONSE_COLS: ["id", "firstName", "lastName", "email", "image", "city", "subdivision", "messagesReadAt", 
    "notifyOnComments", "newslettersOptIn", "country", "redirectUrl", "type", "title", "phoneNumber", "streetName", 
    "zipcode", "agencyPersonalId"],
    _CART_COLS: ["id", "userId", "driveId"],
    _CART_ITEM_COLS: ["unitTax", "id", "driveProductId", "unitPrice", "quantity", "cartId"],
    _ADOPTION_DRIVE_HOLIDAYS_COLS: ["id", "driveId", "holidayId"],
    _ADOPTION_DRIVE_INDIVIDUALS_COLS: ["id", "driveId", "roleId"],
    _SUPPLIER_COLS: ["id", "name", "sortOrder", "currencyId"],
    _CATEGORY_PRODUCT_COLS: ["id", "categoryId", "productId", "sortOrder"]
} 